### ISSUE TITLE
Long running operations are performed immediately in the caller thread

### ISSUE THREAD

**Issue by pilgr** [cesarferreira/RxPaper#1]
As I see in the code 
https://github.com/cesarferreira/RxPaper/blob/master/rxpaper/src/main/java/com/cesarferreira/rxpaper/RxPaper.java#L43
write is performed immediately as `RxPaper.with(ctx).write(key, value)` is called. This should be doing in onSuscribe instead so disk i/o could be postponed and scheduled in the bg thread using Rx.

**Comment by cesarferreira** [comment]
Hey @pilgr, great work on Paper! I've been using it for awhile and I love it :+1: 
Nice catch, I'm adressing this issue right now!

**Comment by pakoito** [comment]
Really important, even just using Observable.defer would be a cleaner fix than doing it onSubscribe.

**Comment by cesarferreira** [comment]
True @pakoito good point.
I guess it's ok now, thanks for the feedback!

**Comment by pakoito** [comment]
Check the comment I left on the commit!
