### ISSUE TITLE
Observable retains Context but doesn't use it

### ISSUE THREAD

**Issue by FranciscoE-Hudl** [cesarferreira/RxPaper#10]
Being the #1 cause of leaks on Android, retaining a Context is rarely recommended. It is still required by the main observable, but it's never used, becoming a pointless pain point: https://github.com/cesarferreira/RxPaper/blob/master/rxpaper/src/main/java/com/cesarferreira/rxpaper/RxPaper.java

Could you please release a new version with that change, and deprecating the old use?

**Comment by diegoRodriguezAguila** [comment]
I've made a pull request to fix this, [Pull Request #11](https://github.com/cesarferreira/RxPaper/pull/11)
