### ISSUE TITLE
No ability to have multiple instances of RxPaper

### ISSUE THREAD

**Issue by Trikke** [cesarferreira/RxPaper#12]
RxPaper contains 2 static fields to hold the instances of the current RxPaper and custom book you'd be using.

``` java
private static RxPaper mRxPaper;
private static String sCustomBook;
```

There are 2 issues with this setup which both relate to having multiple custom books (or preferably, instances of RxPaper)

Problem 1:

```
RxPaper.book("custom-book1").read(...)
RxPaper.book("custom-book2").read(...)
RxPaper.book("custom-book1").read(...)
```

This will instantiate 3 instances on RxPaper (3x overriding the same static field). So if i use 2 custom books i will create a lot of useless instances.

Problem 2:

I can not have multiple classes which each have a separate RxPaper with a custom book because of the above. The last class create will determine which custom book the will all share.

**Comment by Trikke** [comment]
I created a [pull request](https://github.com/cesarferreira/RxPaper/pull/13) for this.

**Comment by cesarferreira** [comment]
@Trikke super sorry for the late response, i was unsubscribed to this repo, dunno why, will check it out now
