### ISSUE TITLE
Respect the Observable contract for errors

### ISSUE THREAD

**Issue by pakoito** [cesarferreira/RxPaper#2]
https://github.com/cesarferreira/RxPaper/blob/master/rxpaper/src/main/java/com/cesarferreira/rxpaper/RxPaper.java#L50

https://github.com/cesarferreira/RxPaper/blob/master/rxpaper/src/main/java/com/cesarferreira/rxpaper/RxPaper.java#L89

https://github.com/cesarferreira/RxPaper/blob/master/rxpaper/src/main/java/com/cesarferreira/rxpaper/RxPaper.java#L104

An exception is an exception, and should come onError.

**Comment by cesarferreira** [comment]
I agree, addressing the issue right now
