### ISSUE TITLE
Observable.create vs Observable.defer

### ISSUE THREAD

**Issue by Trikke** [cesarferreira/RxPaper#4]
This is not really an issue, more of a question. As most people advocate against using Observable.create unless really needed. [link](http://artemzin.com/blog/rxjava-defer-execution-of-function-via-fromcallable/)

What are your opinions on this and why do you use Observable.create in RxPaper?

**Comment by cesarferreira** [comment]
Hey @Trikke sorry for the delayed response.
At the time I used `Observable.create` because I didn't know about the `Observable.defer`, if I was starting the library today I'd use `defer` for sure, thanks for the issue tho :)
