### ISSUE TITLE
getAllKeys() + hasBook() implementation leads to unwanted behaviour

### ISSUE THREAD

**Issue by jensneuse** [cesarferreira/RxPaper#7]
```
public Observable<List<String>> getAllKeys() {

    return Observable.create(new Observable.OnSubscribe<List<String>>() {
        @Override
        public void call(Subscriber<? super List<String>> subscriber) {

            if (!subscriber.isUnsubscribed()) {

                try {
                    List<String> keys;
                    if (hasBook()) {
                        keys = Paper.book(mCustomBook).getAllKeys();
                    } else {
                        keys = Paper.book().getAllKeys();
                    }
                    subscriber.onNext(keys);
                } catch (Exception e) {
                    subscriber.onError(new UnableToPerformOperationException("Can't collect all keys"));
                }

                subscriber.onCompleted();
            }
        }
    });
}
```

private static boolean hasBook() {
        return !TextUtils.isEmpty(mCustomBook);
    }

In my implementation I work with multiple books.
Problem: I don't know at runtime if a book has entries or not.
If I call "getAllKeys()" at a time where a book is empty I get all keys from default book.

I will overcome this problem by not using default book. However, I suggest to just return zero keys if a custom book is empty and not fall back to default book keys.

**Comment by cesarferreira** [comment]
Hey @jnsone11 thanks for opening the issue.

Can you download this version to see if your problem is gone? https://github.com/cesarferreira/RxPaper/tree/feature/get-all-keys-sample

The `sample` project has a "get all keys" button now

**Comment by jensneuse** [comment]
if (hasBook()) {
                            keys = Paper.book(mCustomBook).getAllKeys();
                        } else {
                            keys = Paper.book().getAllKeys();
                        }

This will still return allKeys from default book because hasBook() returns false when mCustomBook im Empty.

**Comment by cesarferreira** [comment]
But if I'm asking for `getAllKeys()`, I'll get what I asked for, the only two options are, with a book or without a book.

I'm not having your issue. If I'm not understanding your problem correctly can you please make a pull request to the `feature/get-all-keys-sample` branch ?
:smiley:  thanks
