### ISSUE TITLE
Initializing Paper too much times?

### ISSUE THREAD

**Issue by diegoRodriguezAguila** [cesarferreira/RxPaper#9]
What is the need to pass a context to RxPaper.with(..) method, which initilalizes Paper.init(...) for every call?, In Paper docs states that Paper.init(context); must be called only once in Application.onCreate(...). I'm temporary workarounding it by creating another initializer, but I think the context is not necesary in any way.

**Comment by cesarferreira** [comment]
Hey @diegoRodriguezAguila you're totally right, my bad! Can you make a PR with your workaround? I'll add you to the contributors! thanks mate

**Comment by diegoRodriguezAguila** [comment]
Well, what I've really done is copy the RxPaper class and straight paste it in my project and modify it. I could make a pull request of the modifications i've done. The structure is such that the `Paper.init(ctx)` its only called in the application creation, and the RxPaper is just what it's supposed to be, a wrapper, and leaving any dependence of a context out of it.

**Comment by diegoRodriguezAguila** [comment]
I've created the pull request [Pull Request Fix Issue #9](https://github.com/cesarferreira/RxPaper/pull/11)

**Comment by diegoRodriguezAguila** [comment]
Hello,
Would you please, publish the changes on a new release, so we can use it in our projects with gradle?
Thanks in advance.

**Comment by cesarferreira** [comment]
The `0.4.1` version is on `mavenCentral` and on `jcenter` since 3rd of July, just confirmed 😃
